### ISSUE TITLE
Densities between 1x and 2x

### ISSUE THREAD

**Issue by strarsis** [SuperOl3g/postcss-image-set-polyfill#8]
Some displays have densities between 1x and 2x (1.3dppx, 1.5dppx) - 
which could show a better result when these use the 2x variant.
How can multiple factors specified? Is this already covered by the specs - and this polyfill?
Specifying the same image file with a different density could be wasteful? 
Not everyone uses the mqpacker PostCSS plugin to consolidate the basically duplicate mediaqueries.

Currently this polyfill doesn't seem to support densities specified with decimal value (e.g. `1.3x` or `1.5x`).

**Comment by SuperOl3g** [comment]
Decimal value isn't supported at this moment, but pull requests are always welcome 🙂 

As far as I know multiple factors isn't specified, but specification is still in draft.

Specifying the same image file with a different density could be wasteful, but it's hard to do it accidentally. Every extra checking will negatively affect the build time, so it's not very important.

I think media queries optimization is excessive because in following the Single Responsibility Principle one plugin must have only one purpose. If you want optimization use plugin for optimization.

**Comment by SuperOl3g** [comment]
Demical densities values support have been added in 75fe5563f51294ad7147ca55cc222449c0746b91
